name: Prompt Reply Workflow

on:
  schedule:
    # [修改] 将 cron 表达式修改为 '0 18 * * *'
    # 这对应的是 UTC 时间的每天18:00，即北京时间 (UTC+8) 的次日凌晨 2:00
    - cron: '0 18 * * *'
  workflow_dispatch:  # 保留手动触发功能

jobs:
  process-prompt-replies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Prompt Reply Action
        uses: ./
        with:
          github-token: ${{ secrets.DEBUG_PAT }}
          data-repo: jifanlin/new
          workflow-type: 'prompt-reply' 